### ISSUE TITLE
Run Failed:CombinedOutput failed: exec: "./tmp_bin": file does not exist

### ISSUE THREAD

**Issue by rioda78** [wandercn/hotbuild#11]
environment
Golang : 1.17.5
os: windows 11

error description 
1. Follow instruction on hotbuild
2. run comand : hotbuild run

then i get that error.

**Comment by wandercn** [comment]
我在最新版本里修复了，你可以试试v1.0.8 
https://github.com/wandercn/hotbuild/releases/tag/v1.0.8

**Comment by wandercn** [comment]
我在windows 7平台测试过没问题了
